version: "3.9"
services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    scale: 2
    depends_on:
     - appdynamics-proxy
  redis:
    image: "redis:alpine"
  loadbalancer:
    image: "dockercloud/haproxy"
    links:
      - web
    ports:
     - "4000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  loadgen:
    build: loadgen
    environment:
      URL: "http://loadbalancer"
      SLEEP: 1
      CURLOPTS: -s
    depends_on:
      - loadbalancer
  appdynamics-proxy:
    image: "appdynamics/dl-proxy"
    ports:
      - "8080:8080"
    environment:
      APPDYNAMICS_TCP_COMM_HOST: 0.0.0.0
      APPDYNAMICS_TCP_COMM_PORT: 8080
